updated reminder.txt
ykdojo/friendlyreminderbot pull request #20
Opened 2022-05-13 13:02 UTC by arth2002

2022-05-13 14:42 UTC, ykdojo approved these changes

2022-05-13 15:57 UTC, arth2002 commented
Hey, I've no idea what to do next?
so please guide me

2022-05-14 03:35 UTC, Pradumnasaraf requested changes
Please don't change the already committed line, add in a new line

- You can click on commit suggestions to fix that

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-05-14 03:35 UTC, Pradumnasaraf commented on reminders.txt
> +Hey human, just remember - no excuses! Dw, you got this 💪
```suggestion
Hey human, remember to be patient, good things take time.
Hey human, just remember - no excuses! Dw, you got this 💪
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-05-14 09:27 UTC, arth2002 commented
Now? 
Why my quote hasn't been added to the reminder.txt yet?
I'm noob so guide me please

2022-05-14 11:12 UTC, Pradumnasaraf commented
> Now? Why my quote hasn't been added to the reminder.txt yet? I'm noob so guide me please

As soon as the PR will get merged into the main branch, it will start show up.

2022-05-14 22:37 UTC, merged

2022-05-15 03:27 UTC, arth2002 commented
> > Now? Why my quote hasn't been added to the reminder.txt yet? I'm noob so guide me please
> 
> As soon as the PR will get merged into the main branch, it will start show up.

Thanks, Buddy for your help